name: Docker Image CI

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get release tag
      id: get_version
      run: |
        # Extract the tag name from GITHUB_REF
        TAG_NAME=$(echo ${{ github.ref }} | sed 's|refs/tags/||')

        # Optional: Remove 'v' prefix if present
        TAG_NAME=${TAG_NAME#v}
        
        echo "RELEASE_VERSION=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Release version: $TAG_NAME"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          jlevangie/lazydj:${{ steps.get_version.outputs.RELEASE_VERSION }}
          jlevangie/lazydj:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
